### ISSUE TITLE
Error: Field deleteOthers: Couldn't find type undefined in any of the schemas

### ISSUE THREAD

**Issue by zelid** [mlipscombe/postgraphile-plugin-nested-mutations#17]
Installed latest version `postgraphile-plugin-nested-mutations@1.0.0-alpha.23` with yarn and getting `Error: Field deleteOthers: Couldn't find type undefined in any of the schemas.` error during Postgraphile start.

Any ideas what's the reason and how to fix?

```
Using ts-node version 8.0.2, typescript version 3.3.3
Error: Field deleteOthers: Couldn't find type undefined in any of the schemas.
    at collectNode (C:\dev\workspace\packages\dmb-server\node_modules\graphql-import\dist\definition.js:101:23)
    at Array.forEach (<anonymous>)
    at collectNewTypeDefinitions (C:\dev\workspace\packages\dmb-server\node_modules\graphql-import\dist\definition.js:50:30)
    at Object.completeDefinitionPool (C:\dev\workspace\packages\dmb-server\node_modules\graphql-import\dist\definition.js:23:41)
    at Object.importSchema (C:\dev\workspace\packages\dmb-server\node_modules\graphql-import\dist\index.js:99:67)
    at Object.<anonymous> (C:\dev\workspace\packages\dmb-server\src\schema.ts:21:69)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Module.m._compile (C:\Users\Alex\AppData\Local\Temp\ts-node-dev-hook-7511520876709679.js:55:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at require.extensions.(anonymous function) (C:\Users\Alex\AppData\Local\Temp\ts-node-dev-hook-7511520876709679.js:57:14)
[ERROR] 17:00:31 Error: Field deleteOthers: Couldn't find type undefined in any of the schemas.
```

**Comment by zelid** [comment]
Solved the issue. Potgraphile.graphql has been generated  and cached with a wrong scalar type for `deleteOthers` field.
